apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    group: {{ .Values.service.group }}
spec:
  ports:
  - port: {{ .Values.service.container.port }}
    targetPort: {{ .Values.service.container.port }}
  selector:
    app: {{ .Values.service.name }}