apiVersion: v2
name: dask                                # Name of this Helm chart
description: A Helm chart for deploying a web application with a Dask cluster to CIRRUS
type: application                         # Application chart (not a library)
version: 0.1.0                            # Chart version, increment when you change templates
appVersion: "1.0.0"                       # Your application version, increment when you update your image