apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.webapp.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.webapp.name }}
    group: {{ .Values.webapp.group }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.webapp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.webapp.name }}
    spec:
      volumes:
        - name: {{ .Values.webapp.nfs.name }}
          nfs:
            server: {{ .Values.webapp.nfs.server }}
            path: {{ .Values.webapp.nfs.path }}
            readOnly: {{ .Values.webapp.nfs.readOnly }}
      containers:
      - name: {{ .Values.webapp.name }}
        image: {{ .Values.webapp.container.image }}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: {{ .Values.webapp.container.requests.memory }}
            cpu: {{ .Values.webapp.container.requests.cpu }}
          limits:
            memory: {{ .Values.webapp.container.limits.memory }}
            cpu: {{ .Values.webapp.container.limits.cpu }}
        ports:
        - containerPort: {{ .Values.webapp.container.port }}
        volumeMounts:
        - name: {{ .Values.webapp.nfs.name }}
          mountPath: {{ .Values.webapp.nfs.mountPath }}