db:
  name: my-database                       # Database cluster name, also used as hostname
  group: my-database                      # Group label for related resources
  instances: 2                            # Number of PostgreSQL servers in the cluster
  size: 10Gi                              # Storage size for the database
  superUser:
    enabled: false                         # Enable superuser access to the database
    usernameKey: username                  # Key in OpenBao for superuser username
    passwordKey: password                  # Key in OpenBao for superuser password
    secretPath: my-path/superuser          # Path in OpenBao where superuser credentials are stored
  app:
    name: my-app-db                       # Database name to create during bootstrap
    usernameKey: username                  # Key in OpenBao for app user username
    passwordKey: password                  # Key in OpenBao for app user password
    secretPath: my-path/appuser            # Path in OpenBao where app user credentials are stored